/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/heart.glb -o src/Heart.jsx -r public -k 
Author: omarelone (https://sketchfab.com/omarelone)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pumping-heart-model-6f815b9822dc479eae0a17b8dcab9c75
Title: PUMPING HEART MODEL
*/
import * as THREE from 'three'
import React, { useCallback, useEffect, useMemo, useRef } from 'react'
import { useGLTF, useAnimations, SpotLight, Text, Sparkles } from '@react-three/drei'
import { useFrame, useLoader } from '@react-three/fiber';
import circleImg from './assets/circle.png'
export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/heart.glb')
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log(materials);
    materials["Material_41"].metalness = 1
    // materials["Material_41"].roughness = 0.5
    console.log(materials)
    console.log(window.innerWidth)
    actions["Take 001"].fadeIn(0.5).play()
  }, [actions])
  
  return (
    <group scale={window.innerWidth<=768?0.03:0.05} position={[0,window.innerWidth<=768?0:-2,0]} ref={group} {...props} dispose={null}>
      <directionalLight scale={[10,100,100]} position={[-1, window.innerWidth<=768?30.876:38.876, 0.255]} intensity={4000} />
      <directionalLight scale={[10,100,100]} position={[5, window.innerWidth<=768?50.876:50.876, 0.255]} intensity={4000} />

      
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="f6bcb81c5d674405b84df409a29b9a55fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="BASE_HEART" position={[-0.676, 38.876, -0.255]} rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="Object_5" position={[-0.09, 0, -38.876]}>
                    <mesh castShadow name="BASE_HEART_Material_#41_0" geometry={nodes['BASE_HEART_Material_#41_0'].geometry} material={materials.Material_41} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/heart.glb')
